### ISSUE TITLE
你好，用抓包参数生成出来的sign和原始请求上的不一致啊

### ISSUE THREAD

**Issue by ttcly** [n1ptune/jdSign#1]
你好，用抓包参数生成出来的sign和原始请求上的不一致啊

**Comment by n1ptune** [comment]
你是直接调用getSign接口吗？那时间戳和sv都不一样的，抓包的话直接替换getSign函数里面的data

**Comment by n1ptune** [comment]
> 你好，用抓包参数生成出来的sign和原始请求上的不一致啊

你是直接调用getSign接口吗？那时间戳和sv都不一样的，抓包的话直接替换getSign函数里面的data

**Comment by ttcly** [comment]
我把getSign方法里面的时间戳和sv都写死了，配置成抓包里面的数据，结果生成的sign跟抓包生成的sign的不一致

**Comment by n1ptune** [comment]
> 我把getSign方法里面的时间戳和sv都写死了，配置成抓包里面的数据，结果生成的sign跟抓包生成的sign的不一致
感谢指出，已修复

**Comment by n1ptune** [comment]
> 我把getSign方法里面的时间戳和sv都写死了，配置成抓包里面的数据，结果生成的sign跟抓包生成的sign的不一致

感谢指出已修复，我这边测试无误

**Comment by ttcly** [comment]
我怎么测试还是不对呢
    functionId = "queryTemplates"
    clientVersion = "11.8.3"
    client = "android"
    uuid = "EWDvCzcyZNZsYtHwEQHwEK=="
    body = '{"appType":"jdapp","enableZip":"1","systemCode":"shareorder"}'

st=1684321304163 sv=101 生成出来sign=2d52a0fc956d630fadc7b4e0efc431fc
接口里面是st=1684321304163&sign=21e997caed08a743210512cf6a9d1be2&sv=101

感谢指导

**Comment by ttcly** [comment]
我调so生成出来也是2d52a0fc956d630fadc7b4e0efc431fc。但是用生成的sign调接口就是600，神奇了

**Comment by n1ptune** [comment]
> 

> 我怎么测试还是不对呢 functionId = "queryTemplates" clientVersion = "11.8.3" client = "android" uuid = "EWDvCzcyZNZsYtHwEQHwEK==" body = '{"appType":"jdapp","enableZip":"1","systemCode":"shareorder"}'
> 
> st=1684321304163 sv=101 生成出来sign=2d52a0fc956d630fadc7b4e0efc431fc 接口里面是st=1684321304163&sign=21e997caed08a743210512cf6a9d1be2&sv=101
> 
> 感谢指导
我这边测试没问题啊，直接调so和我生成的一样的
```
这是直接调so
05-18 21:43:30.649 21057 21057 I SignJni : st=1684321304163&sign=2d52a0fc956d630fadc7b4e0efc431fc&sv=101

我的接口
TenMagic16
st=1684321304163&sign=2d52a0fc956d630fadc7b4e0efc431fc&sv=101
````

**Comment by n1ptune** [comment]
> 我怎么测试还是不对呢 functionId = "queryTemplates" clientVersion = "11.8.3" client = "android" uuid = "EWDvCzcyZNZsYtHwEQHwEK==" body = '{"appType":"jdapp","enableZip":"1","systemCode":"shareorder"}'
> 
> st=1684321304163 sv=101 生成出来sign=2d52a0fc956d630fadc7b4e0efc431fc 接口里面是st=1684321304163&sign=21e997caed08a743210512cf6a9d1be2&sv=101
> 
> 感谢指导

你在改sv的时候是不是没有改offset和encryptid直接改的sv？

**Comment by ttcly** [comment]
我用接口和so生成出来也都是2d52a0fc956d630fadc7b4e0efc431fc。说明算法是没问题的。但是调jd接口报签名错误，还没查到原因。

**Comment by n1ptune** [comment]
> 我用接口和so生成出来也都是2d52a0fc956d630fadc7b4e0efc431fc。说明算法是没问题的。但是调jd接口报签名错误，还没查到原因。

没问题我调接口是200，你是不是数据传错了

**Comment by ttcly** [comment]
这是我用charles抓取的jd请求
<img width="1426" alt="截屏2023-05-21 09 10 36" src="https://github.com/n1ptune/jdSign/assets/13999665/8f8a9e26-a00f-4e50-ba00-4afa8534f95b">
<img width="1404" alt="截屏2023-05-21 09 14 21" src="https://github.com/n1ptune/jdSign/assets/13999665/7574daae-b583-4e15-830d-8c165eab8ded">


url: https://api.m.jd.com/client.action?functionId=queryTemplates&lmt=0&clientVersion=11.8.3&build=98749&client=android&partner=vivo&sdkVersion=28&lang=zh_CN&harmonyOs=0&networkType=wifi&uts=0f31TVRjBSsqndu4%2FjgUPz6uymy50MQJrmW0uRApZq8q59TVC0B4j%2FUHItxQVKkb5MqM21xyBODMCGxkVMS7ZH0SNCnOuWoLtY0EmXXP1s%2BvlnkWlSVqIgtCtBorrXjAIusrXR2Gj0FmpbbIqaAHV6uRX0iKF6pgovcgSNwhRJ3phjdDA1uQ27Hcp21QRMTJaqMcHHSDrVPeN0I8Mhs6%2BA%3D%3D&uemps=0-0-2&ext=%7B%22prstate%22%3A%220%22%2C%22pvcStu%22%3A%221%22%2C%22cfgExt%22%3A%22%7B%5C%22privacyOffline%5C%22%3A%5C%220%5C%22%7D%22%7D&avifSupport=1&eid=eidA1e88812301scsg0%2FSwlNQ5mXShacW4mwUbINQNMYerErWC68QTUzrOaLfiNdwhw8r2VOjqeTGhGTNuP1D9QePBRdumYw4hu82Mqsc8BtrCEDt%2FZJ&ef=1&ep=%7B%22hdid%22%3A%22JM9F1ywUPwflvMIpYPok0tt5k9kW4ArJEU3lfLhxBqw%3D%22%2C%22ts%22%3A1684321189497%2C%22ridx%22%3A-1%2C%22cipher%22%3A%7B%22area%22%3A%22CV83Cv8yDzu5XzK%3D%22%2C%22d_model%22%3A%22U00jHzu4CJK%3D%22%2C%22wifiBssid%22%3A%22dW5hbw93bq%3D%3D%22%2C%22osVersion%22%3A%22EG%3D%3D%22%2C%22d_brand%22%3A%22c2Pjc3VkZm%3D%3D%22%2C%22screen%22%3A%22CJYmCMe5CNK%3D%22%2C%22uuid%22%3A%22EWDvCzcyZNZsYtHwEQHwEK%3D%3D%22%2C%22aid%22%3A%22EWDvCzcyZNZsYtHwEQHwEK%3D%3D%22%2C%22openudid%22%3A%22EWDvCzcyZNZsYtHwEQHwEK%3D%3D%22%7D%2C%22ciphertype%22%3A5%2C%22version%22%3A%221.2.0%22%2C%22appname%22%3A%22com.jingdong.app.mall%22%7D&st=1684321304163&sign=21e997caed08a743210512cf6a9d1be2&sv=101

其中: functionId = "queryTemplates"
clientVersion = "11.8.3"
client = "android"
uuid = "EWDvCzcyZNZsYtHwEQHwEK=="
body = '{"appType":"jdapp","enableZip":"1","systemCode":"shareorder"}'

生产出来的sign为2d52a0fc956d630fadc7b4e0efc431fc。charles抓取的sign是21e997caed08a743210512cf6a9d1be2。并不一致，是我哪个参数取错了吗。感谢

**Comment by n1ptune** [comment]
> 这是我用charles抓取的jd请求 <img alt="截屏2023-05-21 09 10 36" width="1426" src="https://user-images.githubusercontent.com/13999665/239715233-8f8a9e26-a00f-4e50-ba00-4afa8534f95b.png"> <img alt="截屏2023-05-21 09 14 21" width="1404" src="https://user-images.githubusercontent.com/13999665/239715285-7574daae-b583-4e15-830d-8c165eab8ded.png">
> 
> url: https://api.m.jd.com/client.action?functionId=queryTemplates&lmt=0&clientVersion=11.8.3&build=98749&client=android&partner=vivo&sdkVersion=28&lang=zh_CN&harmonyOs=0&networkType=wifi&uts=0f31TVRjBSsqndu4%2FjgUPz6uymy50MQJrmW0uRApZq8q59TVC0B4j%2FUHItxQVKkb5MqM21xyBODMCGxkVMS7ZH0SNCnOuWoLtY0EmXXP1s%2BvlnkWlSVqIgtCtBorrXjAIusrXR2Gj0FmpbbIqaAHV6uRX0iKF6pgovcgSNwhRJ3phjdDA1uQ27Hcp21QRMTJaqMcHHSDrVPeN0I8Mhs6%2BA%3D%3D&uemps=0-0-2&ext=%7B%22prstate%22%3A%220%22%2C%22pvcStu%22%3A%221%22%2C%22cfgExt%22%3A%22%7B%5C%22privacyOffline%5C%22%3A%5C%220%5C%22%7D%22%7D&avifSupport=1&eid=eidA1e88812301scsg0%2FSwlNQ5mXShacW4mwUbINQNMYerErWC68QTUzrOaLfiNdwhw8r2VOjqeTGhGTNuP1D9QePBRdumYw4hu82Mqsc8BtrCEDt%2FZJ&ef=1&ep=%7B%22hdid%22%3A%22JM9F1ywUPwflvMIpYPok0tt5k9kW4ArJEU3lfLhxBqw%3D%22%2C%22ts%22%3A1684321189497%2C%22ridx%22%3A-1%2C%22cipher%22%3A%7B%22area%22%3A%22CV83Cv8yDzu5XzK%3D%22%2C%22d_model%22%3A%22U00jHzu4CJK%3D%22%2C%22wifiBssid%22%3A%22dW5hbw93bq%3D%3D%22%2C%22osVersion%22%3A%22EG%3D%3D%22%2C%22d_brand%22%3A%22c2Pjc3VkZm%3D%3D%22%2C%22screen%22%3A%22CJYmCMe5CNK%3D%22%2C%22uuid%22%3A%22EWDvCzcyZNZsYtHwEQHwEK%3D%3D%22%2C%22aid%22%3A%22EWDvCzcyZNZsYtHwEQHwEK%3D%3D%22%2C%22openudid%22%3A%22EWDvCzcyZNZsYtHwEQHwEK%3D%3D%22%7D%2C%22ciphertype%22%3A5%2C%22version%22%3A%221.2.0%22%2C%22appname%22%3A%22com.jingdong.app.mall%22%7D&st=1684321304163&sign=21e997caed08a743210512cf6a9d1be2&sv=101
> 
> 其中: functionId = "queryTemplates" clientVersion = "11.8.3" client = "android" uuid = "EWDvCzcyZNZsYtHwEQHwEK==" body = '{"appType":"jdapp","enableZip":"1","systemCode":"shareorder"}'
> 
> 生产出来的sign为2d52a0fc956d630fadc7b4e0efc431fc。charles抓取的sign是21e997caed08a743210512cf6a9d1be2。并不一致，是我哪个参数取错了吗。感谢



> 这是我用charles抓取的jd请求 <img alt="截屏2023-05-21 09 10 36" width="1426" src="https://user-images.githubusercontent.com/13999665/239715233-8f8a9e26-a00f-4e50-ba00-4afa8534f95b.png"> <img alt="截屏2023-05-21 09 14 21" width="1404" src="https://user-images.githubusercontent.com/13999665/239715285-7574daae-b583-4e15-830d-8c165eab8ded.png">
> 
> url: https://api.m.jd.com/client.action?functionId=queryTemplates&lmt=0&clientVersion=11.8.3&build=98749&client=android&partner=vivo&sdkVersion=28&lang=zh_CN&harmonyOs=0&networkType=wifi&uts=0f31TVRjBSsqndu4%2FjgUPz6uymy50MQJrmW0uRApZq8q59TVC0B4j%2FUHItxQVKkb5MqM21xyBODMCGxkVMS7ZH0SNCnOuWoLtY0EmXXP1s%2BvlnkWlSVqIgtCtBorrXjAIusrXR2Gj0FmpbbIqaAHV6uRX0iKF6pgovcgSNwhRJ3phjdDA1uQ27Hcp21QRMTJaqMcHHSDrVPeN0I8Mhs6%2BA%3D%3D&uemps=0-0-2&ext=%7B%22prstate%22%3A%220%22%2C%22pvcStu%22%3A%221%22%2C%22cfgExt%22%3A%22%7B%5C%22privacyOffline%5C%22%3A%5C%220%5C%22%7D%22%7D&avifSupport=1&eid=eidA1e88812301scsg0%2FSwlNQ5mXShacW4mwUbINQNMYerErWC68QTUzrOaLfiNdwhw8r2VOjqeTGhGTNuP1D9QePBRdumYw4hu82Mqsc8BtrCEDt%2FZJ&ef=1&ep=%7B%22hdid%22%3A%22JM9F1ywUPwflvMIpYPok0tt5k9kW4ArJEU3lfLhxBqw%3D%22%2C%22ts%22%3A1684321189497%2C%22ridx%22%3A-1%2C%22cipher%22%3A%7B%22area%22%3A%22CV83Cv8yDzu5XzK%3D%22%2C%22d_model%22%3A%22U00jHzu4CJK%3D%22%2C%22wifiBssid%22%3A%22dW5hbw93bq%3D%3D%22%2C%22osVersion%22%3A%22EG%3D%3D%22%2C%22d_brand%22%3A%22c2Pjc3VkZm%3D%3D%22%2C%22screen%22%3A%22CJYmCMe5CNK%3D%22%2C%22uuid%22%3A%22EWDvCzcyZNZsYtHwEQHwEK%3D%3D%22%2C%22aid%22%3A%22EWDvCzcyZNZsYtHwEQHwEK%3D%3D%22%2C%22openudid%22%3A%22EWDvCzcyZNZsYtHwEQHwEK%3D%3D%22%7D%2C%22ciphertype%22%3A5%2C%22version%22%3A%221.2.0%22%2C%22appname%22%3A%22com.jingdong.app.mall%22%7D&st=1684321304163&sign=21e997caed08a743210512cf6a9d1be2&sv=101
> 
> 其中: functionId = "queryTemplates" clientVersion = "11.8.3" client = "android" uuid = "EWDvCzcyZNZsYtHwEQHwEK==" body = '{"appType":"jdapp","enableZip":"1","systemCode":"shareorder"}'
> 
> 生产出来的sign为2d52a0fc956d630fadc7b4e0efc431fc。charles抓取的sign是21e997caed08a743210512cf6a9d1be2。并不一致，是我哪个参数取错了吗。感谢

我看错了status_code是200，但是还会报错，我排查下
status_code ==> 200
{"code":"604","echo":"decrypt failed"}

**Comment by n1ptune** [comment]
> 这是我用charles抓取的jd请求 <img alt="截屏2023-05-21 09 10 36" width="1426" src="https://user-images.githubusercontent.com/13999665/239715233-8f8a9e26-a00f-4e50-ba00-4afa8534f95b.png"> <img alt="截屏2023-05-21 09 14 21" width="1404" src="https://user-images.githubusercontent.com/13999665/239715285-7574daae-b583-4e15-830d-8c165eab8ded.png">
> 
> url: https://api.m.jd.com/client.action?functionId=queryTemplates&lmt=0&clientVersion=11.8.3&build=98749&client=android&partner=vivo&sdkVersion=28&lang=zh_CN&harmonyOs=0&networkType=wifi&uts=0f31TVRjBSsqndu4%2FjgUPz6uymy50MQJrmW0uRApZq8q59TVC0B4j%2FUHItxQVKkb5MqM21xyBODMCGxkVMS7ZH0SNCnOuWoLtY0EmXXP1s%2BvlnkWlSVqIgtCtBorrXjAIusrXR2Gj0FmpbbIqaAHV6uRX0iKF6pgovcgSNwhRJ3phjdDA1uQ27Hcp21QRMTJaqMcHHSDrVPeN0I8Mhs6%2BA%3D%3D&uemps=0-0-2&ext=%7B%22prstate%22%3A%220%22%2C%22pvcStu%22%3A%221%22%2C%22cfgExt%22%3A%22%7B%5C%22privacyOffline%5C%22%3A%5C%220%5C%22%7D%22%7D&avifSupport=1&eid=eidA1e88812301scsg0%2FSwlNQ5mXShacW4mwUbINQNMYerErWC68QTUzrOaLfiNdwhw8r2VOjqeTGhGTNuP1D9QePBRdumYw4hu82Mqsc8BtrCEDt%2FZJ&ef=1&ep=%7B%22hdid%22%3A%22JM9F1ywUPwflvMIpYPok0tt5k9kW4ArJEU3lfLhxBqw%3D%22%2C%22ts%22%3A1684321189497%2C%22ridx%22%3A-1%2C%22cipher%22%3A%7B%22area%22%3A%22CV83Cv8yDzu5XzK%3D%22%2C%22d_model%22%3A%22U00jHzu4CJK%3D%22%2C%22wifiBssid%22%3A%22dW5hbw93bq%3D%3D%22%2C%22osVersion%22%3A%22EG%3D%3D%22%2C%22d_brand%22%3A%22c2Pjc3VkZm%3D%3D%22%2C%22screen%22%3A%22CJYmCMe5CNK%3D%22%2C%22uuid%22%3A%22EWDvCzcyZNZsYtHwEQHwEK%3D%3D%22%2C%22aid%22%3A%22EWDvCzcyZNZsYtHwEQHwEK%3D%3D%22%2C%22openudid%22%3A%22EWDvCzcyZNZsYtHwEQHwEK%3D%3D%22%7D%2C%22ciphertype%22%3A5%2C%22version%22%3A%221.2.0%22%2C%22appname%22%3A%22com.jingdong.app.mall%22%7D&st=1684321304163&sign=21e997caed08a743210512cf6a9d1be2&sv=101
> 
> 其中: functionId = "queryTemplates" clientVersion = "11.8.3" client = "android" uuid = "EWDvCzcyZNZsYtHwEQHwEK==" body = '{"appType":"jdapp","enableZip":"1","systemCode":"shareorder"}'
> 
> 生产出来的sign为2d52a0fc956d630fadc7b4e0efc431fc。charles抓取的sign是21e997caed08a743210512cf6a9d1be2。并不一致，是我哪个参数取错了吗。感谢

还是参数传递的问题， uuid在body里面不是ep里面那个uuid，我这边测试正常了，我添加了一个test.py脚本你可以用那个来试一试
```
st=1684684691878&sign=fa6f96bd54d521b340cd662e331ad7a5&sv=110
{"code":"0"}
```

**Comment by ttcly** [comment]
好的，感谢，已经可以

**Comment by Su1008** [comment]
你好 按照流程下来 还是失败的
uuid在body没有呀 只有ep里面有 接口似乎更新了

**Comment by fuuhoo** [comment]
接口应该是更新了不行了吧？

**Comment by fuuhoo** [comment]
没有uuid的怎么样处理呢
